import type { Patient } from "@/types/patient"
import type { CareProfessional } from "@/types/care-professional"

// Mock patient data with avatars
export const mockPatients: Patient[] = [
  {
    id: "p1",
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1975-05-15",
    nhsNumber: "123 456 7890",
    address: "123 Main St, London, UK",
    phoneNumber: "07700 900123",
    email: "john.smith@example.com",
    emergencyContact: "Jane Smith: 07700 900124",
    medicalConditions: ["Diabetes Type 2", "Hypertension"],
    medications: ["Metformin", "Lisinopril"],
    allergies: ["Penicillin"],
    notes: "Patient prefers afternoon appointments.",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    gpConnect: {
      gpName: "Dr. Sarah Johnson",
      gpPractice: "Highfield Medical Centre",
      gpAddress: "45 High Street, London, UK",
      gpPhoneNumber: "020 7946 0123",
      gpEmail: "reception@highfieldmedical.co.uk",
      lastAppointment: "2023-05-10",
      nextAppointment: "2023-07-15",
      nhsConnectStatus: "connected",
      referralStatus: "Completed",
    },
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-06-10T14:15:00Z",
  },
  {
    id: "p2",
    firstName: "Sarah",
    lastName: "Johnson",
    dateOfBirth: "1982-08-23",
    nhsNumber: "234 567 8901",
    address: "456 Oak Ave, Manchester, UK",
    phoneNumber: "07700 900125",
    email: "sarah.johnson@example.com",
    emergencyContact: "Michael Johnson: 07700 900126",
    medicalConditions: ["Asthma", "Anxiety"],
    medications: ["Ventolin", "Sertraline"],
    allergies: ["Latex", "Peanuts"],
    notes: "Patient requires an interpreter for appointments.",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    gpConnect: {
      gpName: "Dr. James Williams",
      gpPractice: "Oakwood Surgery",
      gpAddress: "78 Oak Road, Manchester, UK",
      gpPhoneNumber: "0161 496 0123",
      gpEmail: "info@oakwoodsurgery.co.uk",
      lastAppointment: "2023-06-05",
      nextAppointment: "2023-08-10",
      nhsConnectStatus: "connected",
      referralStatus: "Active",
    },
    createdAt: "2023-02-20T09:15:00Z",
    updatedAt: "2023-06-15T11:30:00Z",
  },
  {
    id: "p3",
    firstName: "Michael",
    lastName: "Brown",
    dateOfBirth: "1990-11-12",
    nhsNumber: "345 678 9012",
    address: "789 Pine Ln, Birmingham, UK",
    phoneNumber: "07700 900127",
    email: "michael.brown@example.com",
    emergencyContact: "Emily Brown: 07700 900128",
    medicalConditions: ["Depression", "Lower Back Pain"],
    medications: ["Fluoxetine", "Ibuprofen"],
    allergies: [],
    notes: "Patient prefers email communication.",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
    gpConnect: {
      gpName: "Dr. Emily Taylor",
      gpPractice: "Pinewood Health Centre",
      gpAddress: "23 Pine Street, Birmingham, UK",
      gpPhoneNumber: "0121 496 0123",
      gpEmail: "reception@pinewoodhealth.co.uk",
      lastAppointment: "2023-05-20",
      nhsConnectStatus: "pending",
      referralStatus: "Awaiting response",
    },
    createdAt: "2023-03-10T14:45:00Z",
    updatedAt: "2023-06-05T16:20:00Z",
  },
  {
    id: "p4",
    firstName: "Emily",
    lastName: "Wilson",
    dateOfBirth: "1965-04-30",
    nhsNumber: "456 789 0123",
    address: "101 Elm St, Glasgow, UK",
    phoneNumber: "07700 900129",
    email: "emily.wilson@example.com",
    emergencyContact: "Robert Wilson: 07700 900130",
    medicalConditions: ["Rheumatoid Arthritis", "Osteoporosis"],
    medications: ["Methotrexate", "Calcium supplements", "Vitamin D"],
    allergies: ["Sulfa drugs"],
    notes: "Patient uses a wheelchair and requires accessible facilities.",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    gpConnect: {
      gpName: "Dr. Robert Smith",
      gpPractice: "Elmwood Medical Practice",
      gpAddress: "56 Elm Road, Glasgow, UK",
      gpPhoneNumber: "0141 496 0123",
      gpEmail: "admin@elmwoodmedical.co.uk",
      lastAppointment: "2023-06-15",
      nextAppointment: "2023-07-30",
      nhsConnectStatus: "connected",
      referralStatus: "Completed",
    },
    createdAt: "2023-01-25T11:30:00Z",
    updatedAt: "2023-06-20T10:45:00Z",
  },
  {
    id: "p5",
    firstName: "Robert",
    lastName: "Taylor",
    dateOfBirth: "1988-09-18",
    nhsNumber: "567 890 1234",
    address: "202 Cedar Rd, Edinburgh, UK",
    phoneNumber: "07700 900131",
    email: "robert.taylor@example.com",
    emergencyContact: "Olivia Taylor: 07700 900132",
    medicalConditions: ["Epilepsy"],
    medications: ["Lamotrigine"],
    allergies: ["Shellfish"],
    notes: "Patient requires reminder calls for appointments.",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/men/67.jpg",
    gpConnect: {
      gpName: "Dr. Olivia Brown",
      gpPractice: "Cedar Health Centre",
      gpAddress: "34 Cedar Lane, Edinburgh, UK",
      gpPhoneNumber: "0131 496 0123",
      gpEmail: "info@cedarhealth.co.uk",
      lastAppointment: "2023-04-25",
      nextAppointment: "2023-07-25",
      nhsConnectStatus: "disconnected",
      referralStatus: "Pending",
    },
    createdAt: "2023-02-15T13:20:00Z",
    updatedAt: "2023-05-30T15:10:00Z",
  },
]

// Mock care professional data with avatars
export const mockCareProfessionals: CareProfessional[] = [
  {
    id: "cp-001",
    first_name: "Sarah",
    last_name: "Johnson",
    email: "sarah.johnson@example.com",
    phone: "07700 900123",
    role: "Registered Nurse",
    status: "active",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    createdAt: new Date("2023-01-15T10:30:00Z"),
    updatedAt: new Date("2023-03-20T14:15:00Z"),
  },
  {
    id: "cp-002",
    first_name: "James",
    last_name: "Williams",
    email: "james.williams@example.com",
    phone: "07700 900124",
    role: "Care Assistant",
    status: "active",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    createdAt: new Date("2023-01-20T11:45:00Z"),
    updatedAt: new Date("2023-03-22T09:30:00Z"),
  },
  {
    id: "cp-003",
    first_name: "Emily",
    last_name: "Brown",
    email: "emily.brown@example.com",
    phone: "07700 900125",
    role: "Physiotherapist",
    status: "active",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    createdAt: new Date("2023-02-05T09:15:00Z"),
    updatedAt: new Date("2023-04-01T16:20:00Z"),
  },
  {
    id: "cp-004",
    first_name: "Robert",
    last_name: "Smith",
    email: "robert.smith@example.com",
    phone: "07700 900126",
    role: "Occupational Therapist",
    status: "inactive",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
    createdAt: new Date("2023-02-10T14:30:00Z"),
    updatedAt: new Date("2023-03-25T11:10:00Z"),
  },
  {
    id: "cp-005",
    first_name: "Olivia",
    last_name: "Taylor",
    email: "olivia.taylor@example.com",
    phone: "07700 900127",
    role: "Mental Health Nurse",
    status: "active",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/women/22.jpg",
    createdAt: new Date("2023-02-15T10:00:00Z"),
    updatedAt: new Date("2023-04-05T15:45:00Z"),
  },
  {
    id: "cp-006",
    first_name: "Michael",
    last_name: "Anderson",
    email: "michael.anderson@example.com",
    phone: "07700 900128",
    role: "Speech Therapist",
    status: "active",
    tenantId: "demo-tenant",
    avatarUrl: "https://randomuser.me/api/portraits/men/67.jpg",
    createdAt: new Date("2023-03-01T13:20:00Z"),
    updatedAt: new Date("2023-04-10T09:30:00Z"),
  },
]

